AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to Create an Elastic File System and its mount targets in subnets.'
Parameters:
  EfsName:
    Description: The unique name of the EFS in a region. It must indicate the location of the mount point of the EFS.
    Type: String
    Default: efs
    MaxLength: 16
    ConstraintDescription: must be in the format like "efs0"
  Encryption:
    Type: String
    Description: Encrypt the EFS or not
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  KmsKey:
    Description: The AWS KMS key ids for the encryption
    Type: String
    Default: ' '
    MaxLength: 2048
    ConstraintDescription: must be an id of AWS KMS
  EfsMode:
    Description: The performance mode of the EFS
    Type: String
    Default: generalPurpose
    AllowedValues:
      - generalPurpose
      - maxIO
    ConstraintDescription: must be either generalPurpose or maxIO
  IoMode:
    Description: The Throughput Mode of the EFS
    Type: String
    Default: bursting
    AllowedValues:
      - bursting
      - provisioned
    ConstraintDescription: must be either bursting or provisioned
  ProvisionedIo:
    Description: The Provisioned Throughput in Mbps of the EFS. Only available when the IO mode is set to provisioned.
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 1024
    ConstraintDescription: must be number between 1 - 1024
  Lifecycle:
    Description: The Lifecycle policy of the EFS. The EFS won't transfer files to IA storage when it is set to 0.
    Default: 7d
    Type: String
    AllowedValues:
      - disable
      - 7d
      - 14d
      - 30d
      - 60d
      - 90d
    ConstraintDescription: must be number defined in the lifecycle mapping
  # TargetEC2Ids:
  #   Description: The EC2 ids as mount target.
  #   Default: ''
  #   Type: List<AWS::EC2::Instance::Id>
  VpcName:
    Description: The NewVpcName in the vpc CloudFormation stack.
    Type: String
    MinLength: 1
    MaxLength: 32
  SubnetNamePrefix:
    Description: The prefix of the subnets
    Default: 'subnet'
    Type: String
    MinLength: 1
    MaxLength: 32
  Level:
    Default: test
    Description: The Level keyword of the security groups.
    Type: String
    AllowedValues:
    - prod
    - test
    - uat
  TagLevel:
    Default: Test
    Description: The Level tag of resourses.
    Type: String
    AllowedValues:
    - Production
    - Test
    - UAT
  TheAuthor:
    Default: DevOps
    Description: The person's initail for the Author tag of the resources 
    Type: String
    MinLength: 2
    MaxLength: 6
  # Nested template locations
  TemplateS3URL:
    Default: ""
    Description: The S3 HTTP domain for all sub-templates
    Type: String
  TemplateS3DomainSuffix:
    Default: ""
    Description: The S3 HTTPS domain suffix for mainland China is ".cn". Leave it to empty for other regions.
    Type: String
    AllowedValues:
      - ""
      - ".cn"
  TemplateFolder:
    Default: "nested"
    Description: The S3 bucket path sub-templates
    Type: String
    # MinLength: 1
# Data mappings
Mappings:
  TransitionInDays:
    disable:
      Days: 0
    7d:
      Days: AFTER_7_DAYS
    14d:
      Days: AFTER_14_DAYS
    30d:
      Days: AFTER_30_DAYS
    60d:
      Days: AFTER_60_DAYS
    90d:
      Days: AFTER_90_DAYS
Conditions:
  SetKms:
    !And
      - !Equals [!Ref Encryption, 'true']
      - !Not [ !Equals [!Ref KmsKey, ' '] ]
  SetLifecycle:
    !Not [!Equals [!Ref Lifecycle, disable]]
  SetProvisionedThroughputInMibps:
    !And
      - !Equals [ !Ref IoMode, provisioned ]
      - !Not [ !Equals [!Ref ProvisionedIo, 0] ]
# Resources for Creation
Resources:
  # Create a EFS drive
  ElasticFileSystem1:
    Type: AWS::EFS::FileSystem
    Properties: 
      Encrypted: !Ref Encryption
      KmsKeyId: 
        !If # KMS key is only needed when the "Encrypted" is set to true and you want to KMS
          - SetKms
          - KmsKeyId: !Ref KmsKey
          - !Ref "AWS::NoValue"
      LifecyclePolicies:
        !If 
          - SetLifecycle
          -
            - TransitionToIA: !FindInMap [ 'TransitionInDays', !Ref Lifecycle, 'Days' ]
          - !Ref "AWS::NoValue"
      PerformanceMode: !Ref EfsMode
      ThroughputMode: !Ref IoMode
      ProvisionedThroughputInMibps: # Only available when ThroughputMode is set to provisioned
        !If
          - SetProvisionedThroughputInMibps
          - !Ref ProvisionedIo
          - !Ref "AWS::NoValue"
      FileSystemTags:
        - Key: Name
          Value: !Sub '${VpcName}-${EfsName}'
        - Key: Author
          Value: !Ref TheAuthor
        - Key: Level
          Value: !Ref TagLevel
        - Key: VPC
          Value: !Ref VpcName
  # Create child resources by calling nested stacks
  # Create EFS mount targets in the VPC private subnets
  EfsTargets1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateS3URL}.amazonaws.com${TemplateS3DomainSuffix}/${TemplateFolder}/efs_target_nested.yml"
      TimeoutInMinutes: 2
      Parameters:
        EfsId: !Ref ElasticFileSystem1
        EfsName: !Ref EfsName
        VpcName: !Ref VpcName
        SecurityGroups:
          Fn::ImportValue: !Sub '${VpcName}-efs-security-1-id'
        Subnets:
          Fn::Join:
            - ','
            - - Fn::ImportValue: !Sub '${VpcName}-${SubnetNamePrefix}-id-a-pub-1'
              - Fn::ImportValue: !Sub '${VpcName}-${SubnetNamePrefix}-id-b-pub-1'
              - Fn::ImportValue: !Sub '${VpcName}-${SubnetNamePrefix}-id-c-pub-1'
        Level: !Ref Level
        TheAuthor: !Ref TheAuthor
        TagLevel: !Ref TagLevel
    DependsOn: "ElasticFileSystem1"
Outputs:
  ElasticFileSystem:
    Description: The resource ID of the EFS
    Value: !Ref ElasticFileSystem1
    Export:
      Name: !Sub '${VpcName}-${EfsName}-id'
  SubnetNames:
    Description: The full prefix of subnet targets
    Value: !Sub '${VpcName}-${SubnetNamePrefix}'
