AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template of creating a subnet group for ElastiCache clusters.'
Parameters:
  GroupName:
    Type: String
    Description: The suffix of the subnet group
    Default: subg
    MinLength: 1
    MaxLength: 16
    ConstraintDescription: must be characters or numbers or hyphens
  GroupDesc:
    Type: String
    Description: The description of the subnet group
    MinLength: 8
    MaxLength: 64
    ConstraintDescription: must be characters or numbers or hyphens
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The private subnets associate to the subnet group in the VPC.
    ConstraintDescription: must be at most one subnet in each AZ
  VpcName:
    Description: The NewVpcName in the vpc CloudFormation stack.
    Type: String
    MinLength: 1
    MaxLength: 32
    ConstraintDescription: must be a name of an existing VPC.
  TemplateS3URL:
    Default: ""
    Description: The S3 HTTP domain for all sub-templates
    Type: String
    # MinLength: 1
Resources:
  # Create a subnet group for ElastiCache clusters
  CacheSubnetGroup:
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties:
      CacheSubnetGroupName: !Sub '${VpcName}-cache-${GroupName}'
      Description: !Ref GroupDesc
      SubnetIds: !Ref Subnets
Outputs:
  CacheSubnetGroup:
    Description: The logic ID of the ElastiCache subnet group
    Value:
      Ref: CacheSubnetGroup
    Export:
      Name: !Sub '${VpcName}-cache-${GroupName}-id'
