AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation of creating public and private Route Tables for a VPC in an AWS region."
Parameters:
  RouteTableName:
    Description: The Route Table Name for the vpc.
    Default: route-table
    Type: String
    MaxLength: 32
  RouteTableNum:
    Description: The number of the public route table
    Default: 1
    Type: Number
    MinValue: 1
    MaxValue: 10
  RoutePeerConnection:
    Description: The VPC Peering connection id for the Route Table.
    Default: ""
    Type: String
    MaxLength: 32
  RoutePeerConnIP:
    Description: The IP CIDR block of the source VPC.
    Default: "10.0.0.0/16"
    Type: String
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(0)\\.(0)/(16)"
    ConstraintDescription: must be a valid IP CIDR range that ends with /16 like x.x.0.0/16
  VpcId:
    Description: The VpcId from the main VPC CloudFormation stack.
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: must be the id of an existing VPC.
  VpcCidr:
    Description: The CIDR range of the VPC
    Type: String
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(0)\\.(0)/(16)"
    ConstraintDescription: must be a valid IP CIDR range that ends with /16 like x.x.0.0/16
  VpcName:
    Description: The NewVpcName in the vpc CloudFormation stack.
    Type: String
    MinLength: 1
    MaxLength: 32
  SubnetName:
    Description: The common name of the subnets
    Default: "subnet"
    Type: String
    MinLength: 1
    MaxLength: 32
  InternetGatewayId:
    Description: The resource id of the internet gateway
    Type: String
    MinLength: 8
    MaxLength: 32
  # Uniserval parameters
  Level:
    Default: prod
    Description: The Level keyword of the security groups.
    Type: String
    AllowedValues:
      - prod
      - test
      - uat
  TheAuthor:
    Default: DevOps
    Description: The person's initail for the Author tag of the resources
    Type: String
    MinLength: 2
    MaxLength: 6
  TagLevel:
    Default: Test
    Description: The Level tag of resourses.
    Type: String
  # Nested template locations
  TemplateS3URL:
    Default: ""
    Description: The S3 HTTP domain for all sub-templates
    Type: String
    # MinLength: 1
  TemplateFolder:
    Default: "nested"
    Description: The S3 bucket path sub-templates
    Type: String
    # MinLength: 1
Conditions:
  CondAddPeerConn: !Not [!Equals [!Ref RoutePeerConnection, ""]]
Resources:
  # Create the default Public Route Table for the VPC
  publicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub "${VpcName}-pub-rt-${RouteTableNum}"
        - Key: Author
          Value:
            Ref: TheAuthor
  # Add the route rule to the Internet Gateway to the Public Route Table
  addRouteToInternetGateway:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      #DestinationIpv6CidrBlock: '::/0'
      GatewayId: !Ref InternetGatewayId
      RouteTableId:
        Ref: publicRouteTable
  # Add the Peering connection to the Public Route Table
  addRouteToPeerConnection:
    Type: AWS::EC2::Route
    Condition: CondAddPeerConn
    Properties:
      DestinationCidrBlock: !Ref RoutePeerConnIP
      #DestinationIpv6CidrBlock: '::/0'
      GatewayId: !Ref RoutePeerConnection
      RouteTableId:
        Ref: publicRouteTable
  # Create the default Private Route Table for the VPC
  privateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub "${VpcName}-pri-rt-${RouteTableNum}"
        - Key: Author
          Value:
            Ref: TheAuthor
  # Create child stacks by calling nested stacks
  # Create 3 public subnets and 3 private subnets in each AZ
  mainVpcSubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateS3URL}.amazonaws.com/${TemplateFolder}/subnet_nested.yml"
      TimeoutInMinutes: 10
      Parameters:
        VpcId: !Ref VpcId
        VpcCidr: !Ref VpcCidr
        VpcName: !Ref VpcName
        RouteTableIdPub: !Ref publicRouteTable
        RouteTableIdPriv: !Ref privateRouteTable
        SubnetName:
          Fn::Sub:
            - ${VpcName}-${SubnetName}
            - VpcName: !Ref VpcName
              SubnetName: !Ref "SubnetName"
        TemplateS3URL: !Ref TemplateS3URL
        TemplateFolder: !Ref TemplateFolder
        TheAuthor: !Ref TheAuthor
        Level: !Ref Level
        TagLevel: !Ref TagLevel
    DependsOn:
      - publicRouteTable
      - privateRouteTable
Outputs:
  NewRouteTableId:
    Description: The resource_id of the new Route table of the VPC
    Value: !Ref publicRouteTable
    Export:
      Name: !Sub "${VpcName}-${RouteTableName}-${RouteTableNum}-PublicRouteTableId"
  NewPrivateRouteTableId:
    Description: The resource_id of the new Route table of the VPC
    Value: !Ref privateRouteTable
    Export:
      Name: !Sub "${VpcName}-${RouteTableName}-${RouteTableNum}-PrivateRouteTableId"
