AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation of Creating WAFs for a region."
Parameters:
  RegionCode:
    Description: The Recollect internal short region code.
    Type: String
    Default: useast1
    MinLength: 1
    MaxLength: 16
    ConstraintDescription: must be a string like ap-southeast-2 to apsoutheast2
  WafScope:
    Description: The WAF Regex Pattern Set Scope value.
    Type: String
    Default: REGIONAL
    AllowedValues:
      - REGIONAL
      - CLOUDFRONT
    ConstraintDescription: must be REGIONAL or CLOUDFRONT
  UaRegexSetArn:
    Description: The Arn of Regex pattern set for User-Agent in the region
    Type: String
    ConstraintDescription: must be an ARN of Regex pattern sets in the region
  Level:
    Default: test
    Description: The Level keyword of the security groups.
    Type: String
    AllowedValues:
      - prod
      - test
      - uat
  TagLevel:
    Default: Test
    Description: The Level tag of resourses.
    Type: String
    AllowedValues:
      - Production
      - Test
      - UAT
  TheAuthor:
    Default: DevOps
    Description: The person's initail for the Author tag of the resources
    Type: String
    MinLength: 2
    MaxLength: 6
# Data mappings
#Mappings:

# Resources for Creation
Resources:
  # Create the default WAF for web applications
  DefaultWebACLPublic:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: DefaultWebACLPublic
      Scope: !Ref WafScope
      Description: This is the default WebACL for public websites
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: DefaultWebACLPublicMetric
      Rules:
        # Rule to block access from France and Russia
        - Name: BlockCountries
          Priority: 0
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockCountriesMetric
          Statement:
            GeoMatchStatement:
              CountryCodes:
                - RU
                - FR
        # Rule to block Bad Bots
        - Name: BlockBadBots
          Priority: 1
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockBadBotsMetric
          Statement:
            RegexPatternSetReferenceStatement:
              Arn: !Ref UaRegexSetArn
              FieldToMatch:
                SingleHeader: "User-Agent"
              TextTransformations:
                - Priority: 1
                  Type: NONE
        # AWS managed common rules
        - Name: RuleWithAWSManagedRules
          Priority: 2
          OverrideAction:
            Count: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithAWSManagedRulesMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules: []
        # Rule to block XSS attack
        - Name: BlockXssAttack
          Priority: 3
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockXssAttackMetric
          Statement:
            XssMatchStatement:
              FieldToMatch:
                AllQueryArguments: {}
              TextTransformations:
                - Priority: 1
                  Type: NONE
Outputs:
  DefaultWebACLPublicId:
    Description: The logic id of the default public Web ACL WAF
    Value: !GetAtt DefaultWebACLPublic.Id
    Export:
      Name: !Sub "${RegionCode}-waf-web-1-id"
  # DefaultWebACLPublicCapacity: # Error: Not sure what data type of the Capacity (not a string/array/list)
  #   Description: The Capacity of the default public Web ACL WAF
  #   Value: !Select [ 0, !GetAtt DefaultWebACLPublic.Capacity ]
  #   Export:
  #     Name: !Sub '${RegionCode}-waf-1-capacity'
